import type { PreRegistrationFieldRecord, PreRegistrationSettings } from "@/lib/types";

export const defaultPreRegistrationSettings: PreRegistrationSettings = {
  formEnabled: true,
  formEyebrow: "Hemen Kayit",
  formTitle: "Cocugunuz icin ilk adimi burada atiyoruz.",
  formDescription:
    "Hemen Kayit Ol butonuna bastiginizda acilan bu modal uzerinden basvurunuzu iletebilirsiniz. Form kesin kayit degildir; once incelenir, sonra uygun programa aktivasyon yapilir.",
  formLogoUrl: "",
  formLogoPath: "",
  kvkkTitle: "KVKK Aydinlatma Metni",
  kvkkBody:
    "Kisisel verileriniz, basvurunuzu degerlendirmek, sizinle iletisime gecmek ve uygun spor programina yonlendirme yapmak amaciyla islenir. Verileriniz ilgili mevzuata uygun sekilde saklanir ve yetkisiz ucuncu kisilerle paylasilmaz.",
  kvkkCheckboxLabel: "KVKK aydinlatma metnini okudum ve kabul ediyorum.",
  parentPermissionTitle: "Veli Izin Belgesi",
  parentPermissionBody:
    "Velisi oldugum ogrenci adina on kayit basvurusu yapilmasina, verilen bilgilerin dogruluguna ve kurum tarafindan degerlendirilmesine onay veriyorum.",
  parentPermissionCheckboxLabel: "Veli izin belgesini okudum ve kabul ediyorum.",
  successMessage:
    "On kaydiniz alindi. Ekibimiz en kisa surede sizinle iletisime gececek.",
  helperNote:
    "IP adresiniz ve tarayici / cihaz bilgileriniz guvenlik ve basvuru dogrulama amaciyla kaydedilir.",
};

export function mergePreRegistrationSettings(
  base: PreRegistrationSettings,
  incoming: Partial<PreRegistrationSettings> | null | undefined,
) {
  if (!incoming) {
    return base;
  }

  return {
    ...base,
    ...incoming,
  };
}

export const defaultPreRegistrationFields: PreRegistrationFieldRecord[] = [
  {
    id: "system-student-tc-identity-no",
    fieldKey: "studentTcIdentityNo",
    label: "TC Kimlik No",
    inputType: "text",
    helperText: "Opsiyonel · 11 haneli",
    placeholder: "11 haneli TC Kimlik No",
    options: [],
    required: false,
    active: true,
    sortOrder: 10,
    section: "student",
    system: true,
    source: "default",
  },
  {
    id: "system-student-full-name",
    fieldKey: "studentFullName",
    label: "Ad Soyad",
    inputType: "text",
    helperText: "",
    placeholder: "Ogrencinin adi ve soyadi",
    options: [],
    required: true,
    active: true,
    sortOrder: 20,
    section: "student",
    system: true,
    source: "default",
  },
  {
    id: "system-student-gender",
    fieldKey: "studentGender",
    label: "Cinsiyet",
    inputType: "select",
    helperText: "",
    placeholder: "",
    options: ["male", "female"],
    required: true,
    active: true,
    sortOrder: 30,
    section: "student",
    system: true,
    source: "default",
  },
  {
    id: "system-student-birth-date",
    fieldKey: "studentBirthDate",
    label: "Dogum Tarihi",
    inputType: "date",
    helperText: "2 - 18 yas arasi",
    placeholder: "",
    options: [],
    required: true,
    active: true,
    sortOrder: 40,
    section: "student",
    system: true,
    source: "default",
  },
  {
    id: "system-student-photo",
    fieldKey: "studentPhoto",
    label: "Fotograf",
    inputType: "file",
    helperText: "JPG, PNG, WebP · Max 5MB",
    placeholder: "",
    options: [],
    required: false,
    active: true,
    sortOrder: 50,
    section: "student",
    system: true,
    source: "default",
  },
  {
    id: "system-note",
    fieldKey: "note",
    label: "Aciklama",
    inputType: "textarea",
    helperText: "",
    placeholder: "Varsa belirtmek istediginiz notlar...",
    options: [],
    required: false,
    active: true,
    sortOrder: 60,
    section: "student",
    system: true,
    source: "default",
  },
  {
    id: "system-father-name",
    fieldKey: "fatherName",
    label: "Baba Ad Soyad",
    inputType: "text",
    helperText: "",
    placeholder: "Baba ad soyad",
    options: [],
    required: false,
    active: true,
    sortOrder: 70,
    section: "parent",
    system: true,
    source: "default",
  },
  {
    id: "system-father-phone",
    fieldKey: "fatherPhone",
    label: "Baba Telefon",
    inputType: "phone",
    helperText: "",
    placeholder: "05XX XXX XX XX",
    options: [],
    required: false,
    active: true,
    sortOrder: 80,
    section: "parent",
    system: true,
    source: "default",
  },
  {
    id: "system-father-occupation",
    fieldKey: "fatherOccupation",
    label: "Baba Meslek",
    inputType: "text",
    helperText: "",
    placeholder: "Baba meslek",
    options: [],
    required: false,
    active: true,
    sortOrder: 90,
    section: "parent",
    system: true,
    source: "default",
  },
  {
    id: "system-mother-name",
    fieldKey: "motherName",
    label: "Anne Ad Soyad",
    inputType: "text",
    helperText: "",
    placeholder: "Anne ad soyad",
    options: [],
    required: false,
    active: true,
    sortOrder: 100,
    section: "parent",
    system: true,
    source: "default",
  },
  {
    id: "system-mother-phone",
    fieldKey: "motherPhone",
    label: "Anne Telefon",
    inputType: "phone",
    helperText: "",
    placeholder: "05XX XXX XX XX",
    options: [],
    required: false,
    active: true,
    sortOrder: 110,
    section: "parent",
    system: true,
    source: "default",
  },
  {
    id: "system-mother-occupation",
    fieldKey: "motherOccupation",
    label: "Anne Meslek",
    inputType: "text",
    helperText: "",
    placeholder: "Anne meslek",
    options: [],
    required: false,
    active: true,
    sortOrder: 120,
    section: "parent",
    system: true,
    source: "default",
  },
  {
    id: "system-parent-email",
    fieldKey: "parentEmail",
    label: "E-posta",
    inputType: "email",
    helperText: "",
    placeholder: "veli@eposta.com",
    options: [],
    required: true,
    active: true,
    sortOrder: 130,
    section: "parent",
    system: true,
    source: "default",
  },
  {
    id: "system-parent-whatsapp",
    fieldKey: "parentWhatsapp",
    label: "WhatsApp / Telefon",
    inputType: "phone",
    helperText: "",
    placeholder: "05XX XXX XX XX",
    options: [],
    required: true,
    active: true,
    sortOrder: 140,
    section: "parent",
    system: true,
    source: "default",
  },
  {
    id: "system-address",
    fieldKey: "address",
    label: "Ikametgah Adresi",
    inputType: "textarea",
    helperText: "",
    placeholder: "Ikametgah adresi",
    options: [],
    required: true,
    active: true,
    sortOrder: 150,
    section: "parent",
    system: true,
    source: "default",
  },
  {
    id: "system-emergency-contact",
    fieldKey: "emergencyContact",
    label: "Acil Durumda Aranacak Kisi",
    inputType: "text",
    helperText: "",
    placeholder: "Acil durumda aranacak kisi",
    options: [],
    required: true,
    active: true,
    sortOrder: 160,
    section: "parent",
    system: true,
    source: "default",
  },
  {
    id: "system-branch-id",
    fieldKey: "branchId",
    label: "Ilgilenilen Sube",
    inputType: "select",
    helperText: "",
    placeholder: "",
    options: [],
    required: true,
    active: true,
    sortOrder: 170,
    section: "application",
    system: true,
    source: "default",
  },
  {
    id: "system-season-id",
    fieldKey: "seasonId",
    label: "Sezon",
    inputType: "select",
    helperText: "",
    placeholder: "",
    options: [],
    required: true,
    active: true,
    sortOrder: 180,
    section: "application",
    system: true,
    source: "default",
  },
  {
    id: "system-program-id",
    fieldKey: "programId",
    label: "Program",
    inputType: "select",
    helperText: "",
    placeholder: "",
    options: [],
    required: true,
    active: true,
    sortOrder: 190,
    section: "application",
    system: true,
    source: "default",
  },
];

export function getPreRegistrationInputTypeLabel(inputType: PreRegistrationFieldRecord["inputType"]) {
  switch (inputType) {
    case "textarea":
      return "Uzun metin";
    case "date":
      return "Tarih";
    case "select":
      return "Secimli liste";
    case "email":
      return "E-posta";
    case "phone":
      return "Telefon";
    case "file":
      return "Dosya / Gorsel";
    default:
      return "Kisa metin";
  }
}
