/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    headlines: Headline;
    programs: Program;
    galleries: Gallery;
    applications: Application;
    categories: Category;
    locations: Location;
    'site-pages': SitePage;
    testimonials: Testimonial;
    partners: Partner;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    headlines: HeadlinesSelect<false> | HeadlinesSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    galleries: GalleriesSelect<false> | GalleriesSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'site-pages': SitePagesSelect<false> | SitePagesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Ana sayfa manşetlerini ve ziyaretçinin okuyacağı haber detaylarını yönetin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headlines".
 */
export interface Headline {
  id: number;
  /**
   * Editör incelemeye gönderir; Admin hazır içeriği yayınlar.
   */
  workflowStatus: 'draft' | 'review';
  title: string;
  /**
   * Boş bırakılırsa başlıktan otomatik oluşturulur. Örnek: bahar-donemi-kayitlari
   */
  slug: string;
  publishedAt: string;
  kicker?: string | null;
  summary?: string | null;
  /**
   * Metni seçerek kalınlık, renk, yazı tipi, bağlantı ve hizalama uygulayabilirsiniz.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  /**
   * Medya seçilmediyse kullanılacak görsel adresi.
   */
  externalImage?: string | null;
  imageAlt: string;
  linkType: 'program' | 'custom' | 'none';
  program?: (number | null) | Program;
  customUrl?: string | null;
  buttonLabel?: string | null;
  isActive: boolean;
  order: number;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    /**
     * Boş bırakılırsa sayfanın kendi public adresi kullanılır.
     */
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Sitede yayınlanan seyahat, kamp ve atölye programlarını yönetin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  /**
   * Editör incelemeye gönderir; Admin hazır içeriği yayınlar.
   */
  workflowStatus: 'draft' | 'review';
  title: string;
  slug: string;
  availabilityStatus: 'open' | 'soon' | 'full' | 'draft';
  summary: string;
  category: number | Category;
  location?: (number | null) | Location;
  region: 'domestic' | 'international';
  audience: string;
  season?: string | null;
  featured?: boolean | null;
  price?: {
    showPrice?: boolean | null;
    label?: string | null;
    amount?: number | null;
  };
  dates?:
    | {
        label: string;
        capacityStatus?: ('available' | 'limited' | 'full') | null;
        id?: string | null;
      }[]
    | null;
  cover?: (number | null) | Media;
  /**
   * Medya seçilmediyse kullanılacak görsel adresi.
   */
  externalCover?: string | null;
  coverAlt: string;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  details?:
    | {
        heading: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  included?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  excluded?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    /**
     * Boş bırakılırsa sayfanın kendi public adresi kullanılır.
     */
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  type: 'travel' | 'workshop' | 'camp' | 'international' | 'seasonal';
  description?: string | null;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  title: string;
  slug: string;
  city: string;
  country: string;
  summary?: string | null;
  cover?: (number | null) | Media;
  /**
   * Medya seçilmediyse kullanılacak görsel adresi.
   */
  externalCover?: string | null;
  mapUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bağımsız galeri sayfaları oluşturun ve diğer sayfalarda yeniden kullanın.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries".
 */
export interface Gallery {
  id: number;
  /**
   * Editör incelemeye gönderir; Admin hazır içeriği yayınlar.
   */
  workflowStatus: 'draft' | 'review';
  title: string;
  slug: string;
  summary?: string | null;
  cover?: (number | null) | Media;
  /**
   * Medya seçilmediyse kullanılacak görsel adresi.
   */
  externalCover?: string | null;
  images: {
    image?: (number | null) | Media;
    externalImage?: string | null;
    alt: string;
    caption?: string | null;
    id?: string | null;
  }[];
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    /**
     * Boş bırakılırsa sayfanın kendi public adresi kullanılır.
     */
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Web sitesi üzerinden gelen bilgi taleplerini ve dönüş durumlarını takip edin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  fullName: string;
  phone: string;
  email?: string | null;
  childAge?: string | null;
  program?: (number | null) | Program;
  programTitle?: string | null;
  message?: string | null;
  kvkkConsent: boolean;
  status: 'new' | 'contacted' | 'follow-up' | 'closed';
  notes?: string | null;
  legacySyncStatus: 'pending' | 'synced' | 'failed';
  legacySyncedAt?: string | null;
  legacySyncMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kurumsal, bilgilendirme ve yasal sayfaları bloklarla oluşturun ve menülerde yönetin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-pages".
 */
export interface SitePage {
  id: number;
  /**
   * Editör incelemeye gönderir; Admin hazır içeriği yayınlar.
   */
  workflowStatus: 'draft' | 'review';
  pageType: 'home' | 'landing' | 'custom' | 'system';
  title: string;
  /**
   * Boş bırakılırsa sayfa adından otomatik oluşturulur.
   */
  slug: string;
  /**
   * Ana sayfa için /, sistem sayfaları için /programlar gibi sabit adres.
   */
  systemPath?: string | null;
  hero: {
    style: 'simple' | 'image';
    eyebrow?: string | null;
    heading: string;
    summary?: string | null;
    image?: (number | null) | Media;
    /**
     * Medya seçilmediyse kullanılacak görsel adresi.
     */
    externalImage?: string | null;
    imageAlt?: string | null;
  };
  layout?:
    | (
        | {
            eyebrow?: string | null;
            title?: string | null;
            intro?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            width?: ('narrow' | 'wide') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richContent';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            intro?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            image?: (number | null) | Media;
            /**
             * Medya seçilmediyse kullanılacak görsel adresi.
             */
            externalImage?: string | null;
            imageAlt: string;
            imagePosition?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaText';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            intro?: string | null;
            columns?: ('2' | '3' | '4') | null;
            items: {
              icon?: ('leaf' | 'shield' | 'heart' | 'bike' | 'brush' | 'mountain' | 'plane' | 'sparkles') | null;
              title: string;
              body: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureList';
          }
        | {
            eyebrow?: string | null;
            title: string;
            body?: string | null;
            buttonLabel: string;
            buttonUrl: string;
            tone?: ('green' | 'light') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
        | {
            eyebrow?: string | null;
            title: string;
            body?: string | null;
            showContactDetails?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            intro?: string | null;
            gallery: number | Gallery;
            display?: ('grid' | 'strip') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            intro?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'locationGrid';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            intro?: string | null;
            limit: number;
            id?: string | null;
            blockName?: string | null;
            blockType: 'programGrid';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            intro?: string | null;
            limit: number;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialGrid';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            intro?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'partnerGrid';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            intro?: string | null;
            limit: number;
            id?: string | null;
            blockName?: string | null;
            blockType: 'headlineGrid';
          }
      )[]
    | null;
  /**
   * Ana manşetin altındaki kısa bilgi kartlarını düzenleyin ve sürükleyerek sıralayın.
   */
  homeMetrics?:
    | {
        icon: 'leaf' | 'users' | 'calendar' | 'shield' | 'sparkles' | 'location';
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  homeProcess?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    steps?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  partnerEyebrow?: string | null;
  /**
   * Boş bırakılırsa sayfa adı kullanılır.
   */
  navigationLabel?: string | null;
  showInHeader?: boolean | null;
  headerOrder?: number | null;
  showInFooter?: boolean | null;
  footerOrder?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    /**
     * Boş bırakılırsa sayfanın kendi public adresi kullanılır.
     */
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  title: string;
  body: string;
  parentName: string;
  childInfo?: string | null;
  programName?: string | null;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  title: string;
  logo?: (number | null) | Media;
  url?: string | null;
  order: number;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'form-tracker';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'headlines';
        value: number | Headline;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'galleries';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'site-pages';
        value: number | SitePage;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headlines_select".
 */
export interface HeadlinesSelect<T extends boolean = true> {
  workflowStatus?: T;
  title?: T;
  slug?: T;
  publishedAt?: T;
  kicker?: T;
  summary?: T;
  content?: T;
  image?: T;
  externalImage?: T;
  imageAlt?: T;
  linkType?: T;
  program?: T;
  customUrl?: T;
  buttonLabel?: T;
  isActive?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  workflowStatus?: T;
  title?: T;
  slug?: T;
  availabilityStatus?: T;
  summary?: T;
  category?: T;
  location?: T;
  region?: T;
  audience?: T;
  season?: T;
  featured?: T;
  price?:
    | T
    | {
        showPrice?: T;
        label?: T;
        amount?: T;
      };
  dates?:
    | T
    | {
        label?: T;
        capacityStatus?: T;
        id?: T;
      };
  cover?: T;
  externalCover?: T;
  coverAlt?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  details?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  included?:
    | T
    | {
        item?: T;
        id?: T;
      };
  excluded?:
    | T
    | {
        item?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries_select".
 */
export interface GalleriesSelect<T extends boolean = true> {
  workflowStatus?: T;
  title?: T;
  slug?: T;
  summary?: T;
  cover?: T;
  externalCover?: T;
  images?:
    | T
    | {
        image?: T;
        externalImage?: T;
        alt?: T;
        caption?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  email?: T;
  childAge?: T;
  program?: T;
  programTitle?: T;
  message?: T;
  kvkkConsent?: T;
  status?: T;
  notes?: T;
  legacySyncStatus?: T;
  legacySyncedAt?: T;
  legacySyncMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  description?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  city?: T;
  country?: T;
  summary?: T;
  cover?: T;
  externalCover?: T;
  mapUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-pages_select".
 */
export interface SitePagesSelect<T extends boolean = true> {
  workflowStatus?: T;
  pageType?: T;
  title?: T;
  slug?: T;
  systemPath?: T;
  hero?:
    | T
    | {
        style?: T;
        eyebrow?: T;
        heading?: T;
        summary?: T;
        image?: T;
        externalImage?: T;
        imageAlt?: T;
      };
  layout?:
    | T
    | {
        richContent?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
              content?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        mediaText?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
              content?: T;
              image?: T;
              externalImage?: T;
              imageAlt?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        featureList?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
              columns?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              showContactDetails?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
              gallery?: T;
              display?: T;
              id?: T;
              blockName?: T;
            };
        locationGrid?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
              id?: T;
              blockName?: T;
            };
        programGrid?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        testimonialGrid?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        partnerGrid?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
              id?: T;
              blockName?: T;
            };
        headlineGrid?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
      };
  homeMetrics?:
    | T
    | {
        icon?: T;
        label?: T;
        value?: T;
        id?: T;
      };
  homeProcess?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        steps?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  partnerEyebrow?: T;
  navigationLabel?: T;
  showInHeader?: T;
  headerOrder?: T;
  showInFooter?: T;
  footerOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  parentName?: T;
  childInfo?: T;
  programName?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  title?: T;
  logo?: T;
  url?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site genelinde kullanılan marka, iletişim ve footer bilgilerini yönetin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  footerBrand: string;
  footerHeadline: string;
  copyrightText: string;
  address: string;
  phone: string;
  /**
   * Ülke koduyla, boşluksuz yazın. Örnek: 905551112233
   */
  whatsappNumber: string;
  email: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Ana sayfanın ilk ekranındaki görseli, metinleri ve yönlendirme butonlarını yönetin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  eyebrow: string;
  title: string;
  /**
   * İki veya üç satırı geçmeyen kısa bir tanıtım metni kullanın.
   */
  description: string;
  /**
   * Yatay, yüksek çözünürlüklü ve metnin geleceği sol tarafı sakin bir görsel seçin.
   */
  backgroundImage?: (number | null) | Media;
  backgroundAlt: string;
  overlayStrength: 'light' | 'medium' | 'dark';
  primaryButton: {
    enabled?: boolean | null;
    label: string;
    url: string;
  };
  secondaryButton: {
    enabled?: boolean | null;
    label: string;
    url: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  footerBrand?: T;
  footerHeadline?: T;
  copyrightText?: T;
  address?: T;
  phone?: T;
  whatsappNumber?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  backgroundImage?: T;
  backgroundAlt?: T;
  overlayStrength?: T;
  primaryButton?:
    | T
    | {
        enabled?: T;
        label?: T;
        url?: T;
      };
  secondaryButton?:
    | T
    | {
        enabled?: T;
        label?: T;
        url?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}